name: GHAV Cloudscape 2760 integration core
on:
  push:
    branches:
      - 'codex/ghav-cloudscape2760-*'
permissions:
  contents: read
jobs:
  integTest:
    name: Components integ tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: npm run test:integ -- --shard=${{ matrix.shard }}/${{ strategy.job-total }}

