name: "ghav before: Release"
"on":
  push:
    branches:
      - ghav/dev/2760
    paths:
      - .ghav/before
permissions:
  id-token: write
  contents: read
jobs:
  integTest:
    name: Components integ tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: npm run test:integ
